######################################################################
##
## Filename: afficheur_afficheur_sch_tb.udo
## Created on: Wed May 02 17:32:14 Paris, Madrid (heure d'été) 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
